apiVersion: v1
kind: Service
metadata:
  name: web-httpd-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 10
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: httpd:2.4.55
          ports:
            - containerPort: 80
      nodeSelector:
        role: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 4
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: node:19-alpine3.16
          command: ["sleep", "100000"]
      nodeSelector:
        role: worker
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: db-deployment
# spec:
#   selector:
#     matchLabels:
#       app: db
#   replicas: 4
#   template:
#     metadata:
#       labels:
#         app: db
#     spec:
#       containers:
#         - name: postgres
#           image: postgres:15.2